name: Build and Deploy
on:
  push:
    branches:
      - project-01/eshop
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.TOKEN }}
        build_configuration: production 
        base_href: /angular-practice/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/eshop

permissions:
  contents: write
